FROM node:20.5.0
ENV NODE_ENV=development
WORKDIR /usr/src/app
# COPY . .
# RUN npm install -g vite
# RUN npm install
# EXPOSE 3000
# RUN chown -R node /usr/src/app
# USER node
# CMD ["npm", "run", "dev"]
# CMD